title: Jie Duan/洁 段
description: 
sourcecode: 

permalink: blog/:year/:month/:day/:title
exclude: ["Makefile", "README.md"]

url: "http://AlvaDuan.github.io"
baseurl: ""

author:
  name:
  facebook:
  scholar:

# Build settings
markdown: kramdown
highlighter: rouge

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments:
  provider:
  disqus:
    short_name:
  livefyre:
    site_id:
  intensedebate:
    account:
  facebook:
    appid:
    num_posts: 5
    width: 580
    colorscheme: light

google_analytics: "G-6QRLXK466J"


